theme: jekyll-theme-cayman

# Site settings
title: 欢迎来到Tgotp的博客！
SEOTitle: Tgotp's Blog
header-img: img/home-bg.png
email: tgotp@foxmail.com
description: "关于xd！ | 这里是 @Tgotp 的个人博客，欢迎共同摸鱼。"
keyword: ""
url: "https://Tgotp.github.io"              # your host, for absolute URL
baseurl: ""              # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
weibo_username:     Tgotp
zhihu_username:     Tgotp
github_username:    Tgotp
twitter_username:   Tgotp
